import Link from "next/link";
import { Activity, AlertTriangle, Bot, Boxes, CheckCircle2, Clock3, FileCheck2, Files, FolderGit2, GitPullRequest, MessageSquare, Play, Search, Sparkles, Tags, Workflow } from "lucide-react";
import { Badge, Button, Card, IconTile, PageHeader, Progress, SearchBox, SelectPill } from "@/components/ui";
import { SectionTabs } from "@/components/section-tabs";
import { activityItems, agents, reviews, workflows } from "@/lib/mock-data";

type Section = "activity"|"reviews"|"evaluations"|"documentation"|"workflows"|"agents";

const docRows=[
  ["OAuth 2.0 authentication guide","Authly","Guide","Up to date","2 hours ago"],
  ["API reference","Authly","Reference","Up to date","5 hours ago"],
  ["SDK installation guide","Authly","Guide","Needs update","1 day ago"],
  ["Rate limits and quotas","Authly","Concept","Up to date","2 days ago"],
  ["Deployment with Kubernetes","Authly","Tutorial","Up to date","3 days ago"],
  ["User management","Authly","Guide","Outdated","5 days ago"],
];
const evalRuns=[
  ["run_01H8Z3","PR #142 – OAuth authentication","documentation",12,11,1,92],
  ["run_01H7Y1","Release v1.2.0 notes","release_notes",10,9,1,88],
  ["run_01H6K9","Redis caching guide","documentation",14,14,0,96],
  ["run_01H5Q8","Support response evaluation","support",16,13,3,84],
];

export function ActivitySubpage({kind}:{kind:string}){
 const filters:Record<string,(x:any)=>boolean>={
  "document-changes":x=>x.icon==="file", "workflow-runs":x=>x.icon==="workflow", evaluations:x=>x.title.toLowerCase().includes("evaluation"), support:x=>x.icon==="message", system:x=>x.source==="System"
 };
 const rows=activityItems.filter(filters[kind]??(()=>true));
 const title={"document-changes":"Document changes","workflow-runs":"Workflow runs",evaluations:"Evaluation activity",support:"Support activity",system:"System activity"}[kind]??"Activity";
 return <><PageHeader title={title} subtitle="Focused activity stream using mock Draftly events."/><SectionTabs section="activity"/><div className="mt-4 grid gap-4 xl:grid-cols-[1fr_300px]"><Card className="overflow-hidden"><div className="divide-y divide-border">{(rows.length?rows:activityItems.slice(0,4)).map((e:any)=><Link href={`/activity/${e.id}`} key={e.id} className="flex gap-3 p-4 hover:bg-surface-subtle"><IconTile size="sm"><Activity className="h-4 w-4"/></IconTile><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{e.title}</div><div className="mt-1 text-xs text-foreground-muted">{e.detail}</div><div className="mt-2 flex gap-2"><Badge>{e.source}</Badge><Badge tone="slate">{e.type}</Badge></div></div><span className="text-xs text-foreground-muted">{e.time}</span></Link>)}</div></Card><Card className="p-4"><h3 className="font-semibold">View controls</h3><div className="mt-4 space-y-3"><SearchBox placeholder="Search activity..."/><SelectPill className="w-full">All sources</SelectPill><SelectPill className="w-full">All actors</SelectPill></div></Card></div></>
}

export function ReviewsSubpage({kind}:{kind:string}){
 const map:Record<string,(r:any)=>boolean>={pending:r=>r.status==="Pending", "needs-attention":r=>r.status==="Urgent"||r.status==="Needs changes", approved:r=>r.status==="Approved", rejected:r=>r.status==="Rejected"};
 const rows=reviews.filter(map[kind]??(()=>true));
 const title={pending:"Pending reviews","needs-attention":"Reviews needing attention",approved:"Approved reviews",rejected:"Rejected reviews"}[kind]??"Reviews";
 return <><PageHeader title={title} subtitle="Human-in-the-loop documentation review queue backed by mock review data."/><SectionTabs section="reviews"/><div className="mt-4 space-y-3">{(rows.length?rows:reviews.slice(0,3)).map((r:any)=><Card className="p-4" key={r.id}><div className="flex flex-col gap-4 md:flex-row md:items-center"><IconTile tone={r.status==="Urgent"?"rose":r.status==="Approved"?"green":"blue"}><FileCheck2 className="h-5 w-5"/></IconTile><div className="min-w-0 flex-1"><Link href={`/reviews/${r.id}`} className="font-semibold hover:text-brand">{r.title}</Link><p className="mt-1 text-xs text-foreground-muted">{r.description}</p><div className="mt-2 flex flex-wrap gap-2"><Badge>{r.repo}</Badge><Badge tone="slate">{r.type}</Badge><Badge tone={r.risk==="High"?"rose":r.risk==="Medium"?"amber":"green"}>{r.risk} risk</Badge></div></div><div className="w-full md:w-40"><div className="mb-1 flex justify-between text-xs"><span>Evaluation</span><b>{r.score}%</b></div><Progress value={r.score}/></div><Badge tone={r.status==="Approved"?"green":r.status==="Urgent"?"rose":r.status==="Needs changes"?"amber":"blue"}>{r.status}</Badge></div></Card>)}</div></>
}

export function EvaluationsSubpage({kind}:{kind:string}){
 const title={runs:"Evaluation runs","test-cases":"Test cases",datasets:"Datasets",evaluators:"Evaluators",trends:"Evaluation trends"}[kind]??"Evaluations";
 const content=kind==="runs"?<div className="space-y-3">{evalRuns.map(r=><Link href={`/evaluations/runs/${r[0]}`} key={String(r[0])}><Card className="mb-3 p-4"><div className="grid gap-3 sm:grid-cols-[1fr_auto_auto_auto]"><div><div className="font-semibold">{r[1]}</div><div className="text-xs text-foreground-muted">{r[0]} · {r[2]}</div></div><span className="text-sm">{r[3]} cases</span><Badge tone={Number(r[5])===0?"green":"amber"}>{r[4]} passed</Badge><b>{r[6]}%</b></div></Card></Link>)}</div>:kind==="test-cases"?<div className="grid gap-3 md:grid-cols-2">{["oauth-authentication-add","release-notes-versioning","support-groundedness","api-reference-sync","sdk-example-validity","migration-completeness"].map((x,i)=><Link href={`/evaluations/test-cases/${x}`} key={x}><Card className="p-4"><div className="flex items-start justify-between"><IconTile tone={i===2?"amber":"green"}><CheckCircle2 className="h-5 w-5"/></IconTile><Badge tone={i===2?"amber":"green"}>{i===2?"0.71":"1.00"}</Badge></div><h3 className="mt-4 font-semibold">{x}</h3><p className="mt-1 text-xs text-foreground-muted">Documentation quality test case with expected content, tools, and authoring actions.</p></Card></Link>)}</div>:kind==="datasets"?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{[["Documentation",48,93],["API Reference",22,89],["Tutorials",18,91],["Release Notes",16,87],["Support Responses",14,90],["Knowledge Updates",10,94]].map(x=><Card key={String(x[0])} className="p-4"><IconTile><Boxes className="h-5 w-5"/></IconTile><h3 className="mt-4 font-semibold">{x[0]}</h3><p className="text-xs text-foreground-muted">{x[1]} test cases</p><div className="mt-4"><Progress value={Number(x[2])}/><div className="mt-1 text-right text-xs font-semibold">{x[2]}%</div></div></Card>)}</div>:kind==="evaluators"?<div className="grid gap-3 md:grid-cols-2">{["Correctness evaluator","Completeness evaluator","Grounding evaluator","Consistency evaluator","Documentation quality evaluator","Tool usage evaluator"].map((x,i)=><Card className="p-4" key={x}><div className="flex gap-3"><IconTile tone={i%2?"violet":"blue"}><Sparkles className="h-5 w-5"/></IconTile><div><h3 className="font-semibold">{x}</h3><p className="mt-1 text-xs text-foreground-muted">Strands Eval SDK evaluator · active · threshold {i%2?"0.80":"0.85"}</p></div></div></Card>)}</div>:<Card className="p-5"><h3 className="font-semibold">14-day score trend</h3><div className="mt-6 flex h-52 items-end gap-2">{[58,61,64,70,68,74,78,82,81,86,88,91,92,94].map((v,i)=><div key={i} className="flex-1 rounded-t bg-brand/20" style={{height:`${v}%`}}><div className="h-2 rounded-t bg-brand"/></div>)}</div></Card>;
 return <><PageHeader title={title} subtitle="Inspect quality, failures, and evaluation assets using mock Strands Eval SDK data."/><SectionTabs section="evaluations"/><div className="mt-4">{content}</div></>
}

export function DocumentationSubpage({kind}:{kind:string}){
 const title={"by-repository":"Documentation by repository","by-topic":"Documentation by topic",outdated:"Outdated documentation","recently-updated":"Recently updated documentation"}[kind]??"Documentation";
 if(kind==="by-repository") return <><PageHeader title={title} subtitle="Group project documentation by source repository."/><SectionTabs section="documentation"/><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[["authly/docs",164],["authly/api",82],["authly/sdk",48],["authly/examples",24]].map(x=><Card key={String(x[0])} className="p-5"><IconTile><FolderGit2 className="h-5 w-5"/></IconTile><h3 className="mt-4 font-semibold">{x[0]}</h3><p className="text-xs text-foreground-muted">{x[1]} documents · synced 12 min ago</p><Button className="mt-4">Browse repository</Button></Card>)}</div></>;
 if(kind==="by-topic") return <><PageHeader title={title} subtitle="Browse documentation through Draftly's topic model."/><SectionTabs section="documentation"/><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Authentication",58],["API Reference",42],["Deployment",36],["User Management",28],["SDKs",24],["Billing",20],["Security",18],["Integrations",16]].map(x=><Card key={String(x[0])} className="p-4"><IconTile tone="violet"><Tags className="h-5 w-5"/></IconTile><div className="mt-3 font-semibold">{x[0]}</div><div className="text-xs text-foreground-muted">{x[1]} documents</div></Card>)}</div></>;
 const rows=kind==="outdated"?docRows.filter(r=>r[3]==="Outdated"||r[3]==="Needs update"):docRows;
 return <><PageHeader title={title} subtitle="Search and manage mock project documentation."/><SectionTabs section="documentation"/><Card className="mt-4 overflow-hidden"><div className="divide-y divide-border">{rows.map((r,i)=><Link href="/documentation/oauth-2-0-integration" key={String(r[0])} className="flex flex-col gap-3 p-4 hover:bg-surface-subtle sm:flex-row sm:items-center"><IconTile tone={r[3]==="Outdated"?"rose":r[3]==="Needs update"?"amber":"blue"}><Files className="h-5 w-5"/></IconTile><div className="min-w-0 flex-1"><div className="font-semibold">{r[0]}</div><div className="text-xs text-foreground-muted">{r[1]} · {r[2]}</div></div><Badge tone={r[3]==="Up to date"?"green":r[3]==="Outdated"?"rose":"amber"}>{r[3]}</Badge><span className="text-xs text-foreground-muted">{r[4]}</span></Link>)}</div></Card></>
}

export function WorkflowsSubpage({kind}:{kind:string}){
 const title={active:"Active workflows",paused:"Paused workflows",drafts:"Workflow drafts",templates:"Workflow templates"}[kind]??"Workflows";
 if(kind==="templates") return <><PageHeader title={title} subtitle="Start from production-oriented Draftly workflow templates."/><SectionTabs section="workflows"/><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{["Documentation from PRs","Release notes","Scheduled documentation audit","Support knowledge loop","API reference sync","Legacy docs migration"].map((x,i)=><Card key={x} className="p-5"><IconTile tone={i%2?"violet":"blue"}><Workflow className="h-5 w-5"/></IconTile><h3 className="mt-4 font-semibold">{x}</h3><p className="mt-1 text-xs text-foreground-muted">Preconfigured trigger, agents, evaluation policy, review gate, and delivery action.</p><Link href="/workflows/new"><Button className="mt-4">Use template</Button></Link></Card>)}</div></>;
 const rows=kind==="paused"?workflows.filter((w:any)=>!w[5]):kind==="drafts"?workflows.slice(-2):workflows.filter((w:any)=>w[5]);
 return <><PageHeader title={title} subtitle="Manage automated documentation workflows with mock run state."/><SectionTabs section="workflows"/><div className="mt-4 space-y-3">{rows.map((w:any,i:number)=><Card key={w[0]} className="p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><IconTile tone={i%2?"violet":"blue"}><GitPullRequest className="h-5 w-5"/></IconTile><div className="flex-1"><Link href={`/workflows/${String(w[0]).toLowerCase().replace(/[^a-z0-9]+/g,"-")}`} className="font-semibold hover:text-brand">{w[0]}</Link><p className="text-xs text-foreground-muted">{w[1]}</p></div><div className="text-xs"><span className="text-foreground-muted">Trigger</span><div>{w[2]}</div></div><Badge tone={w[5]?"green":"slate"}>{w[5]?"Active":"Paused"}</Badge></div></Card>)}</div></>
}

export function AgentsSubpage({kind}:{kind:string}){
 const title={active:"Active agents",idle:"Idle agents",templates:"Agent templates"}[kind]??"Agents";
 if(kind==="templates") return <><PageHeader title={title} subtitle="Reusable specialist-agent starting points for Draftly."/><SectionTabs section="agents"/><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{["Documentation specialist","Repository intelligence","Documentation reviewer","Support responder","Memory curator","Evaluation specialist"].map((x,i)=><Card key={x} className="p-5"><IconTile tone={i%3===0?"blue":i%3===1?"violet":"green"}><Bot className="h-5 w-5"/></IconTile><h3 className="mt-4 font-semibold">{x}</h3><p className="mt-1 text-xs text-foreground-muted">Includes recommended skills, tools, model profile, prompt scaffold, and evaluation profile.</p><Link href="/agents/new"><Button className="mt-4">Use template</Button></Link></Card>)}</div></>;
 const rows=agents.filter((a:any)=>kind==="idle"?a[3]!=="Active":a[3]==="Active");
 return <><PageHeader title={title} subtitle="Inspect specialist agents and their current execution state."/><SectionTabs section="agents"/><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((a:any,i:number)=><Card key={a[0]} className="p-4"><div className="flex gap-3"><IconTile tone={i%2?"violet":"blue"}><Bot className="h-5 w-5"/></IconTile><div><Link href={`/agents/${String(a[0]).toLowerCase().replace(/[^a-z0-9]+/g,"-")}`} className="font-semibold hover:text-brand">{a[0]}</Link><div className="mt-1"><Badge tone={a[3]==="Active"?"green":"slate"}>{a[3]}</Badge></div></div></div><p className="mt-4 text-xs leading-5 text-foreground-muted">{a[1]}</p><div className="mt-3 flex flex-wrap gap-1">{String(a[2]).split(", ").map((x:string)=><Badge key={x}>{x}</Badge>)}</div></Card>)}</div></>
}
