"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Activity, Bell, Bot, BookOpen, Boxes, FileCheck2, Files, GitBranch, Grid2X2, Menu, Search, Settings, Sparkles, Sun, Moon, Workflow, X, Command, AlertTriangle } from "lucide-react";
import { ReactNode, useState } from "react";
import { useTheme } from "@/components/theme-provider";

const nav = [
 ["Overview","/",Grid2X2],["Knowledge","/knowledge",BookOpen],["Activity","/activity",Activity],["Reviews","/reviews",FileCheck2],["Evaluations","/evaluations",Boxes],["Documentation","/documentation",Files],["Workflows","/workflows",Workflow],["Agents","/agents",Bot],["Integrations","/integrations",GitBranch],["Settings","/settings",Settings]
] as const;
function Logo(){return <Link href="/" className="flex items-center gap-2"><div className="grid h-9 w-9 place-items-center rounded-lg border-2 border-cyan-400 text-blue-600"><Files className="h-5 w-5"/></div><span className="text-2xl font-semibold">Draftly</span></Link>}
function Navigation({path,onNavigate}:{path:string;onNavigate?:()=>void}){return <nav className="space-y-1 px-3">{nav.map(([label,href,Icon])=>{const active=href==="/"?path===href:path.startsWith(href); return <Link onClick={onNavigate} href={href} key={href} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${active?"bg-blue-600 text-white shadow-sm":"text-slate-600 hover:bg-slate-50"}`}><Icon className="h-[18px] w-[18px]"/><span>{label}</span>{label==="Reviews"&&<span className={`ml-auto rounded-full px-2 py-0.5 text-[11px] ${active?"bg-white/15":"bg-slate-100 text-slate-500"}`}>12</span>}</Link>})}</nav>}
export default function Shell({children}:{children:ReactNode}){
 const path=usePathname(); const {resolvedTheme,toggleTheme}=useTheme(); const [mobile,setMobile]=useState(false); const [notifications,setNotifications]=useState(false); const [command,setCommand]=useState(false); const [profile,setProfile]=useState(false);
 return <div className="min-h-screen bg-background text-foreground lg:grid lg:grid-cols-[214px_1fr]">
   <aside className="fixed inset-y-0 left-0 z-40 hidden w-[214px] flex-col border-r border-border bg-surface lg:flex"><div className="flex h-20 items-center px-5"><Logo/></div><Navigation path={path}/><div className="mt-auto p-4"><Link href="/system" className="block rounded-2xl border border-blue-100 bg-gradient-to-br from-blue-50 to-violet-50 p-4 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-white text-blue-600 shadow-sm"><Sparkles className="h-6 w-6"/></div><p className="mt-3 text-sm font-semibold">Draftly AI Agents<br/>are working for you</p><span className="mt-3 block text-xs font-medium text-blue-600">View system status →</span></Link><button onClick={()=>setProfile(!profile)} className="mt-4 flex w-full items-center gap-3 rounded-xl border border-slate-200 p-3 text-left hover:bg-slate-50"><div className="grid h-9 w-9 place-items-center rounded-full bg-slate-800 text-xs font-semibold text-white">BK</div><div><div className="text-sm font-medium">Bonnie K.</div><div className="text-xs text-slate-500">Admin</div></div></button></div></aside>
   {mobile&&<div className="fixed inset-0 z-[60] bg-slate-950/30 lg:hidden" onClick={()=>setMobile(false)}><aside className="h-full w-[280px] bg-surface shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex h-20 items-center justify-between px-5"><Logo/><button onClick={()=>setMobile(false)} className="rounded-lg p-2"><X className="h-5 w-5"/></button></div><Navigation path={path} onNavigate={()=>setMobile(false)}/></aside></div>}
   <main className="min-w-0 lg:col-start-2"><div className="sticky top-0 z-30 border-b border-border bg-background/95 px-4 py-3 backdrop-blur md:px-7"><div className="mx-auto flex max-w-[1380px] items-center gap-2 sm:gap-4"><button onClick={()=>setMobile(true)} className="grid h-9 w-9 place-items-center rounded-lg border border-border bg-surface lg:hidden"><Menu className="h-5 w-5"/></button><button onClick={()=>setCommand(true)} className="relative flex h-9 min-w-0 flex-1 items-center rounded-lg border border-border bg-surface pl-9 pr-3 text-left text-sm text-slate-400"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2"/><span className="truncate">Search documentation, reviews, workflows...</span><span className="ml-auto hidden items-center gap-1 rounded bg-slate-100 px-2 py-0.5 text-[10px] text-slate-500 sm:inline-flex"><Command className="h-3 w-3"/>K</span></button><button onClick={toggleTheme} aria-label={`Switch to ${resolvedTheme === "dark" ? "light" : "dark"} mode`} title={`Switch to ${resolvedTheme === "dark" ? "light" : "dark"} mode`} className="rounded-lg p-2 text-foreground-secondary hover:bg-surface-subtle">{resolvedTheme === "dark" ? <Sun className="h-5 w-5"/> : <Moon className="h-5 w-5"/>}</button><div className="relative"><button onClick={()=>setNotifications(!notifications)} className="relative rounded-lg p-2 text-slate-600 hover:bg-white"><Bell className="h-5 w-5"/><span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-rose-500 ring-2 ring-white"/></button>{notifications&&<div className="absolute right-0 top-11 w-[320px] max-w-[88vw] rounded-2xl border border-border bg-surface p-3 shadow-xl"><div className="flex items-center justify-between px-1 pb-2"><b className="text-sm">Notifications</b><span className="text-xs text-blue-600">Mark all read</span></div>{[[FileCheck2,"Review required","OAuth authentication update","2m"],[AlertTriangle,"Evaluation failed","API rate limits documentation","18m"],[GitBranch,"Integration issue","Discord connection lost","1h"]].map(([Icon,title,sub,time])=><div key={String(title)} className="flex gap-3 rounded-xl p-2 hover:bg-slate-50"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-blue-50 text-blue-600"><Icon className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="text-xs font-medium">{String(title)}</div><div className="truncate text-xs text-slate-500">{String(sub)}</div></div><span className="text-[10px] text-slate-400">{String(time)}</span></div>)}</div>}</div><button onClick={()=>setProfile(!profile)} className="grid h-9 w-9 place-items-center rounded-full bg-slate-700 text-xs font-medium text-white">BK</button></div></div><div className="mx-auto max-w-[1380px] p-4 md:p-7">{children}</div></main>
   {command&&<div className="fixed inset-0 z-[90] flex justify-center bg-slate-950/30 p-4 pt-[12vh] backdrop-blur-sm" onMouseDown={()=>setCommand(false)}><div className="h-fit w-full max-w-2xl overflow-hidden rounded-2xl border border-slate-200 bg-surface shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="relative border-b border-slate-100"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input autoFocus placeholder="Search Draftly..." className="h-14 w-full pl-12 pr-4 outline-none"/></div><div className="p-3"><div className="px-2 py-1 text-[11px] font-semibold uppercase tracking-wide text-slate-400">Quick results</div>{[[Files,"OAuth 2.0 Integration","Documentation","/documentation/oauth-2-0-integration"],[FileCheck2,"OAuth authentication update","Review","/reviews/oauth"],[Workflow,"PR Documentation","Workflow","/workflows/pr-documentation"],[Bot,"Documentation Agent","Agent","/agents/documentation-agent"]].map(([Icon,label,type,href])=><Link onClick={()=>setCommand(false)} key={String(label)} href={String(href)} className="flex items-center gap-3 rounded-xl p-3 hover:bg-slate-50"><div className="grid h-9 w-9 place-items-center rounded-lg bg-blue-50 text-blue-600"><Icon className="h-4 w-4"/></div><div><div className="text-sm font-medium">{String(label)}</div><div className="text-xs text-slate-500">{String(type)}</div></div></Link>)}</div></div></div>}
   {profile&&<div className="fixed bottom-20 left-4 z-50 w-52 rounded-xl border border-border bg-surface p-2 text-sm shadow-xl lg:bottom-4 lg:left-[222px]"><Link href="/settings" className="block rounded-lg px-3 py-2 hover:bg-slate-50">Profile & workspace</Link><Link href="/settings/notifications" className="block rounded-lg px-3 py-2 hover:bg-slate-50">Notifications</Link><Link href="/settings/audit" className="block rounded-lg px-3 py-2 hover:bg-slate-50">Audit logs</Link></div>}
 </div>
}
