"use client";

import Link from "next/link";
import { ReactNode, useMemo, useState } from "react";
import { ArrowUpRight, ChevronDown, Search, X } from "lucide-react";

type Tone = "blue"|"green"|"amber"|"rose"|"slate"|"violet"|"cyan";

export function Card({children,className=""}:{children:ReactNode,className?:string}) { return <div className={`rounded-2xl border border-border bg-surface shadow-card ${className}`}>{children}</div> }
export function SectionTitle({icon,title,subtitle,action}:{icon?:ReactNode,title:string,subtitle?:string,action?:ReactNode}) { return <div className="flex items-start justify-between gap-3 px-4 pt-4"><div className="flex min-w-0 gap-3">{icon&&<IconTile size="sm">{icon}</IconTile>}<div className="min-w-0"><h3 className="font-semibold text-foreground">{title}</h3>{subtitle && <p className="mt-0.5 text-xs text-foreground-muted">{subtitle}</p>}</div></div>{action}</div> }
export function IconTile({children,tone="blue",size="md",className=""}:{children:ReactNode,tone?:Tone,size?:"sm"|"md"|"lg",className?:string}) { const c={blue:"bg-blue-50 text-blue-600",green:"bg-emerald-50 text-emerald-600",amber:"bg-amber-50 text-amber-600",rose:"bg-rose-50 text-rose-600",slate:"bg-slate-100 text-slate-600",violet:"bg-violet-50 text-violet-600",cyan:"bg-cyan-50 text-cyan-600"}[tone]; const s={sm:"h-8 w-8 rounded-lg",md:"h-11 w-11 rounded-xl",lg:"h-14 w-14 rounded-2xl"}[size]; return <div className={`grid shrink-0 place-items-center ${s} ${c} ${className}`}>{children}</div> }
export function MetricCard({label,value,sub,trend,tone="blue",icon}:{label:string,value:string|number,sub:string,trend?:string,tone?:Exclude<Tone,"slate"|"cyan">,icon?:ReactNode}) {
 const bg={blue:"bg-blue-50 text-blue-600",green:"bg-emerald-50 text-emerald-600",amber:"bg-amber-50 text-amber-600",rose:"bg-rose-50 text-rose-600",violet:"bg-violet-50 text-violet-600"}[tone];
 return <Card className="p-4"><div className="flex items-center gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-full ${bg}`}>{icon}</div><div className="min-w-0 flex-1"><div className="text-xs font-medium text-slate-600">{label}</div><div className="mt-0.5 flex items-center gap-2"><strong className="text-2xl tracking-tight">{value}</strong>{trend&&<span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[11px] font-semibold text-emerald-600">↑ {trend}</span>}</div><div className="truncate text-xs text-foreground-muted">{sub}</div></div></div></Card>
}
export function PageHeader({title,subtitle,actions}:{title:string,subtitle:string,actions?:ReactNode}) { return <div className="mb-4 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><h1 className="text-[27px] font-semibold tracking-tight text-foreground sm:text-[29px]">{title}</h1><p className="mt-0.5 max-w-4xl text-sm text-foreground-muted">{subtitle}</p></div>{actions&&<div className="flex shrink-0 flex-wrap gap-2">{actions}</div>}</div> }
export function Button({children,primary=false,danger=false,className="",onClick,type="button",disabled=false}:{children:ReactNode,primary?:boolean,danger?:boolean,className?:string,onClick?:()=>void,type?:"button"|"submit",disabled?:boolean}) { return <button type={type} disabled={disabled} onClick={onClick} className={`inline-flex h-10 items-center justify-center gap-2 rounded-lg border px-4 text-sm font-medium transition disabled:cursor-not-allowed disabled:opacity-50 ${primary?"border-brand bg-brand text-brand-foreground hover:brightness-110":danger?"border-danger/30 bg-danger-soft text-danger hover:brightness-110":"border-border bg-surface text-foreground-secondary hover:bg-surface-subtle"} ${className}`}>{children}</button> }
export function SearchBox({placeholder="Search...",className="",value,onChange}:{placeholder?:string,className?:string,value?:string,onChange?:(value:string)=>void}) { const [local,setLocal]=useState(""); const current=value??local; return <div className={`relative ${className}`}><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={current} onChange={e=>{setLocal(e.target.value);onChange?.(e.target.value)}} placeholder={placeholder} className="h-10 w-full rounded-lg border border-border bg-input pl-9 pr-3 text-sm text-foreground outline-none focus:border-ring focus:ring-2 focus:ring-ring/20"/></div> }
export function SelectPill({children,className=""}:{children:ReactNode,className?:string}) { return <button className={`inline-flex h-10 items-center justify-between gap-3 whitespace-nowrap rounded-lg border border-border bg-surface px-3 text-sm text-foreground-secondary hover:bg-surface-subtle ${className}`}>{children}<ChevronDown className="h-3.5 w-3.5"/></button> }

type TabItem = string | {label:string;href?:string;count?:number};
export function Tabs({items,active,className=""}:{items:TabItem[],active:string,className?:string}) {
 const [selected,setSelected]=useState(active);
 const normalized=useMemo(()=>items.map(item=>typeof item==="string"?{label:item}:item),[items]);
 return <div className={`relative min-w-0 border-b border-border ${className}`}><div className="flex max-w-full gap-1 overflow-x-auto overscroll-x-contain scroll-smooth px-0 scrollbar-none" role="tablist" aria-label="Page sections">{normalized.map(item=>{const isActive=(item.href?item.label===active:item.label===selected); const classes=`inline-flex min-h-11 shrink-0 items-center gap-2 whitespace-nowrap border-b-2 px-3 py-2.5 text-sm transition ${isActive?"border-brand font-medium text-brand":"border-transparent text-foreground-muted hover:text-foreground"}`; return item.href?<Link key={item.label} href={item.href} className={classes}>{item.label}{item.count!==undefined&&<span className="rounded-full bg-surface-subtle px-1.5 py-0.5 text-[10px] text-foreground-muted">{item.count}</span>}</Link>:<button key={item.label} role="tab" aria-selected={isActive} onClick={()=>setSelected(item.label)} className={classes}>{item.label}{item.count!==undefined&&<span className="rounded-full bg-surface-subtle px-1.5 py-0.5 text-[10px] text-foreground-muted">{item.count}</span>}</button>})}</div><div className="pointer-events-none absolute right-0 top-0 h-10 w-8 bg-gradient-to-l from-surface to-transparent sm:hidden"/></div>
}
export function Badge({children,tone="blue"}:{children:ReactNode,tone?:Tone}) { const c={blue:"bg-blue-50 text-blue-700",green:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700",rose:"bg-rose-50 text-rose-700",slate:"bg-slate-100 text-slate-600",violet:"bg-violet-50 text-violet-700",cyan:"bg-cyan-50 text-cyan-700"}[tone]; return <span className={`inline-flex items-center rounded-md px-2 py-1 text-xs font-medium ${c}`}>{children}</span> }
export function Progress({value,tone="green"}:{value:number,tone?:"green"|"blue"|"violet"|"amber"|"rose"}) { const c={green:"bg-emerald-500",blue:"bg-blue-500",violet:"bg-violet-500",amber:"bg-amber-500",rose:"bg-rose-500"}[tone]; return <div className="h-2 overflow-hidden rounded-full bg-surface-subtle"><div className={`h-full rounded-full transition-all ${c}`} style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div> }
export function TinyLink({children,href}:{children:ReactNode,href?:string}) { const cls="inline-flex items-center gap-1 text-xs font-medium text-blue-600 hover:text-blue-700"; return href?<Link href={href} className={cls}>{children}<ArrowUpRight className="h-3 w-3"/></Link>:<button className={cls}>{children}<ArrowUpRight className="h-3 w-3"/></button> }
export function EmptyState({icon,title,description,action}:{icon:ReactNode,title:string,description:string,action?:ReactNode}) { return <Card className="grid min-h-64 place-items-center p-8 text-center"><div><IconTile size="lg" tone="violet" className="mx-auto">{icon}</IconTile><h3 className="mt-4 font-semibold">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm text-foreground-muted">{description}</p>{action&&<div className="mt-5">{action}</div>}</div></Card> }
export function MockDialog({open,onClose,title,description,children,confirmLabel="Confirm",danger=false,onConfirm}:{open:boolean,onClose:()=>void,title:string,description?:string,children?:ReactNode,confirmLabel?:string,danger?:boolean,onConfirm?:()=>void}) { if(!open)return null; return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/40 p-4 backdrop-blur-sm" onMouseDown={onClose}><Card className="w-full max-w-md p-5 shadow-2xl" ><div onMouseDown={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">{title}</h3>{description&&<p className="mt-1 text-sm text-foreground-muted">{description}</p>}</div><button onClick={onClose} className="rounded-lg p-2 hover:bg-surface-subtle"><X className="h-4 w-4"/></button></div>{children&&<div className="mt-4">{children}</div>}<div className="mt-5 flex justify-end gap-2"><Button onClick={onClose}>Cancel</Button><Button danger={danger} primary={!danger} onClick={()=>{onConfirm?.();onClose()}}>{confirmLabel}</Button></div></div></Card></div> }
export function Skeleton({className=""}:{className?:string}) { return <div className={`animate-pulse rounded-lg bg-surface-subtle ${className}`}/> }
