import Link from "next/link";
import {
  AlertTriangle,
  Bot,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  FileCheck2,
  FilePlus2,
  Filter,
  Github,
  MoreHorizontal,
  RotateCcw,
  Search,
  XCircle,
} from "lucide-react";
import { SectionTabs } from "@/components/section-tabs";
import {
  Button,
  Card,
  MetricCard,
  PageHeader,
  SelectPill,
} from "@/components/ui";
import { reviews } from "@/lib/mock-data";

const tone = (status: string) =>
  (status === "Approved"
    ? "green"
    : status === "Urgent"
      ? "rose"
      : status === "Needs changes"
        ? "amber"
        : "blue") as "green" | "rose" | "amber" | "blue";

const reviewAccent = [
  {
    dot: "bg-violet-500",
    tile: "bg-violet-50 text-violet-500 dark:bg-violet-950/50",
  },
  {
    dot: "bg-amber-500",
    tile: "bg-orange-50 text-orange-500 dark:bg-orange-950/50",
  },
  {
    dot: "bg-rose-500",
    tile: "bg-rose-50 text-rose-500 dark:bg-rose-950/50",
  },
  {
    dot: "bg-emerald-500",
    tile: "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/50",
  },
  {
    dot: "bg-slate-300 dark:bg-slate-600",
    tile: "bg-slate-100 text-slate-500 dark:bg-slate-800",
  },
] as const;

function ReferenceBadge({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex shrink-0 items-center rounded-md bg-violet-50 px-1.5 py-1 text-[10px] font-medium leading-none text-violet-600 dark:bg-violet-950/50 dark:text-violet-300">
      {children}
    </span>
  );
}

function RiskBadge({ risk }: { risk: string }) {
  const styles =
    risk === "High"
      ? "bg-rose-50 text-rose-600 dark:bg-rose-950/50 dark:text-rose-300"
      : risk === "Medium"
        ? "bg-amber-50 text-amber-600 dark:bg-amber-950/50 dark:text-amber-300"
        : "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/50 dark:text-emerald-300";

  return (
    <span
      className={`inline-flex rounded-md px-3 py-2 text-xs font-medium leading-none ${styles}`}>
      {risk}
    </span>
  );
}

function StatusBadge({ status }: { status: string }) {
  const styles = {
    blue: "bg-blue-50 text-blue-600 dark:bg-blue-950/50 dark:text-blue-300",
    green:
      "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/50 dark:text-emerald-300",
    rose: "bg-rose-50 text-rose-600 dark:bg-rose-950/50 dark:text-rose-300",
    amber:
      "bg-amber-50 text-amber-600 dark:bg-amber-950/50 dark:text-amber-300",
  }[tone(status)];

  return (
    <span
      className={`inline-flex rounded-md px-3 py-2 text-xs font-medium leading-none ${styles}`}>
      {status}
    </span>
  );
}

function ReviewRow({
  review,
  index,
}: {
  review: (typeof reviews)[number];
  index: number;
}) {
  const accent = reviewAccent[index] ?? reviewAccent[0];
  const scoreTone =
    review.score < 70
      ? { text: "text-rose-600", fill: "bg-rose-500" }
      : review.score < 80
        ? { text: "text-amber-600", fill: "bg-amber-500" }
        : { text: "text-emerald-600", fill: "bg-emerald-500" };
  const TypeIcon = review.type === "New document" ? FilePlus2 : FileCheck2;

  return (
    <div className="grid min-h-[106px] gap-3 px-5 py-3.5 lg:grid-cols-[minmax(330px,2.35fr)_minmax(135px,1fr)_minmax(125px,.9fr)_minmax(155px,1.15fr)_minmax(92px,.72fr)_minmax(76px,.62fr)_minmax(105px,.8fr)_24px] lg:items-center">
      <div className="grid min-w-0 grid-cols-[9px_46px_minmax(0,1fr)] items-center gap-3">
        <span className={`h-2.5 w-2.5 rounded-full ${accent.dot}`} />
        <span
          className={`grid h-11 w-11 place-items-center rounded-lg ${accent.tile}`}>
          <FileCheck2 aria-hidden="true" className="h-5 w-5" />
        </span>
        <div className="min-w-0">
          <div className="flex min-w-0 items-center gap-2">
            <Link
              href={`/reviews/${review.id}`}
              className="truncate text-sm font-semibold text-foreground hover:text-brand">
              {review.title}
            </Link>
            <ReferenceBadge>{review.ref}</ReferenceBadge>
          </div>
          <p className="mt-1 line-clamp-2 max-w-[325px] text-[11px] leading-[16px] text-foreground-muted">
            {review.description}
          </p>
          <p className="mt-1.5 flex items-center gap-1.5 text-[10px] text-foreground-muted">
            <Bot aria-hidden="true" className="h-3.5 w-3.5" />
            Generated by Documentation Agent
          </p>
        </div>
      </div>

      <div className="min-w-0 text-xs">
        <div className="flex items-center gap-2 font-medium text-foreground">
          <Github aria-hidden="true" className="h-4 w-4" />
          {review.repo}
        </div>
        <div className="mt-1 truncate text-[11px] text-foreground-muted">
          {review.path}
        </div>
      </div>

      <div className="flex min-w-0 items-center gap-2 text-xs text-foreground-secondary">
        <span
          className={`grid h-7 w-7 shrink-0 place-items-center rounded-md ${
            review.type === "New document"
              ? "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/50"
              : "bg-blue-50 text-blue-600 dark:bg-blue-950/50"
          }`}>
          <TypeIcon aria-hidden="true" className="h-4 w-4" />
        </span>
        <span className="max-w-[90px] leading-[18px]">{review.type}</span>
      </div>

      <div className="min-w-0">
        <div className={`text-base font-semibold ${scoreTone.text}`}>
          {review.score}%
        </div>
        <div className="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800">
          <div
            className={`h-full rounded-full ${scoreTone.fill}`}
            style={{ width: `${review.score}%` }}
          />
        </div>
        <div className="mt-1.5 text-[10px] text-foreground-muted">
          {review.evals} evaluations
        </div>
      </div>

      <div>
        <RiskBadge risk={review.risk} />
      </div>
      <span className="text-xs text-foreground-muted">{review.updated}</span>
      <div>
        <StatusBadge status={review.status} />
      </div>
      <button
        type="button"
        aria-label={`More actions for ${review.title}`}
        className="grid h-8 w-8 place-items-center rounded-md text-foreground-muted hover:bg-surface-subtle hover:text-foreground">
        <MoreHorizontal aria-hidden="true" className="h-4 w-4" />
      </button>
    </div>
  );
}

export default function Page() {
  return (
    <>
      <PageHeader
        title="Reviews"
        subtitle="Review AI-generated documentation changes before they become part of your project knowledge."
        actions={
          <div className="flex gap-2">
            <Button>Configure reviews</Button>
            <Button primary>+ New review</Button>
          </div>
        }
      />
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
        <MetricCard
          label="Pending"
          value="12"
          sub="Requires your review"
          icon={<FileCheck2 className="h-5 w-5" />}
        />
        <MetricCard
          label="Urgent"
          value="4"
          sub="High risk or low score"
          tone="rose"
          icon={<AlertTriangle className="h-5 w-5" />}
        />
        <MetricCard
          label="Approved"
          value="47"
          sub="In the last 7 days"
          tone="green"
          icon={<CheckCircle2 className="h-5 w-5" />}
        />
        <MetricCard
          label="Needs changes"
          value="3"
          sub="Returned to agent"
          tone="amber"
          icon={<RotateCcw className="h-5 w-5" />}
        />
        <MetricCard
          label="Rejected"
          value="8"
          sub="In the last 7 days"
          icon={<XCircle className="h-5 w-5" />}
        />
      </div>
      <div className="mt-4">
        <SectionTabs section="reviews" />
      </div>

      <section aria-label="All reviews">
        <div className="my-4 flex flex-wrap items-center gap-3">
          <label className="relative min-w-[260px] flex-1 lg:max-w-[315px]">
            <span className="sr-only">Search reviews</span>
            <Search
              aria-hidden="true"
              className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-foreground-muted"
            />
            <input
              type="search"
              placeholder="Search reviews..."
              className="h-10 w-full rounded-lg border border-border bg-surface pl-10 pr-3 text-sm text-foreground outline-none placeholder:text-foreground-muted focus:border-ring focus:ring-2 focus:ring-ring/20"
            />
          </label>
          <SelectPill className="lg:w-[124px]">Repository</SelectPill>
          <SelectPill className="lg:w-[128px]">Review type</SelectPill>
          <SelectPill className="lg:w-[126px]">Risk level</SelectPill>
          <SelectPill className="lg:w-[121px]">Score</SelectPill>
          <button
            type="button"
            className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-surface px-3.5 text-sm text-foreground-secondary hover:bg-surface-subtle">
            <CalendarDays aria-hidden="true" className="h-4 w-4" />
            All time
            <ChevronDown aria-hidden="true" className="h-3.5 w-3.5" />
          </button>
          <button
            type="button"
            className="ml-auto inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-surface px-4 text-sm text-foreground-secondary hover:bg-surface-subtle">
            <Filter aria-hidden="true" className="h-4 w-4" />
            Filters
          </button>
        </div>

        <Card className="overflow-hidden rounded-xl">
          <div className="hidden min-h-[38px] gap-3 border-b border-border bg-surface-subtle/45 px-5 text-[11px] font-medium text-foreground-muted lg:grid lg:grid-cols-[minmax(330px,2.35fr)_minmax(135px,1fr)_minmax(125px,.9fr)_minmax(155px,1.15fr)_minmax(92px,.72fr)_minmax(76px,.62fr)_minmax(105px,.8fr)_24px] lg:items-center">
            <span>Review</span>
            <span>Repository</span>
            <span>Type</span>
            <span>AI Evaluation</span>
            <span>Risk</span>
            <span>Updated</span>
            <span>Status</span>
            <span />
          </div>
          <div className="divide-y divide-border">
            {reviews.map((review, index) => (
              <ReviewRow key={review.id} review={review} index={index} />
            ))}
          </div>
        </Card>

        <div className="mt-5 flex items-center justify-between pb-1 text-xs text-foreground-muted">
          <span>Showing 1 to 5 of 12 reviews</span>
          <nav aria-label="Reviews pagination" className="flex items-center gap-2">
            <button
              type="button"
              aria-label="Previous page"
              className="grid h-8 w-8 place-items-center rounded-lg border border-border bg-surface hover:bg-surface-subtle">
              <ChevronLeft aria-hidden="true" className="h-4 w-4" />
            </button>
            <button
              type="button"
              aria-current="page"
              className="grid h-8 w-8 place-items-center rounded-lg border border-blue-100 bg-blue-50 font-medium text-blue-600 dark:border-blue-900 dark:bg-blue-950/50">
              1
            </button>
            <button
              type="button"
              className="grid h-8 w-8 place-items-center rounded-lg text-foreground-secondary hover:bg-surface-subtle">
              2
            </button>
            <button
              type="button"
              className="grid h-8 w-8 place-items-center rounded-lg text-foreground-secondary hover:bg-surface-subtle">
              3
            </button>
            <button
              type="button"
              aria-label="Next page"
              className="grid h-8 w-8 place-items-center rounded-lg border border-border bg-surface hover:bg-surface-subtle">
              <ChevronRight aria-hidden="true" className="h-4 w-4" />
            </button>
          </nav>
        </div>
      </section>
    </>
  );
}
