import { Activity, Bot, CalendarDays, CheckCircle2, FileText, Plus, Star, Workflow } from "lucide-react";
import { Badge, Button, Card, MetricCard, PageHeader, Progress, SectionTitle, SelectPill, TinyLink } from "@/components/ui";

const bars=[38,42,48,61,70,51,64,72,49,60,58,66,79,72,80,62];
export default function Page(){return <>
<PageHeader title="Good morning, Bonnie 👋" subtitle="Your documentation is in good shape. Here's what's happening with Draftly." actions={<div className="flex gap-2"><SelectPill><CalendarDays className="h-4 w-4"/>Aug 18, 2026 – Sep 5, 2026</SelectPill><Button primary><Plus className="h-4 w-4"/>New workflow</Button></div>}/>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Documentation" value="318" sub="Total documents" trend="12%" icon={<FileText className="h-5 w-5"/>}/><MetricCard label="Active workflows" value="6" sub="3 running • 3 scheduled" trend="2" tone="violet" icon={<Activity className="h-5 w-5"/>}/><MetricCard label="Review queue" value="12" sub="Pending human review" tone="green" icon={<CheckCircle2 className="h-5 w-5"/>}/><MetricCard label="Avg. evaluation score" value="92%" sub="Across all runs" trend="4%" tone="amber" icon={<Star className="h-5 w-5"/>}/></div>
<div className="mt-4 grid gap-4 xl:grid-cols-[1.55fr_.95fr_.9fr]">
 <div className="space-y-4">
  <Card><SectionTitle icon={<FileText className="h-4 w-4"/>} title="Documentation activity" subtitle="AI-generated and updated documentation over time" action={<SelectPill>Last 14 days</SelectPill>}/><div className="px-5 pb-5 pt-6"><div className="flex h-48 items-end gap-2 border-b border-l border-slate-200 px-3">{bars.map((b,i)=><div key={i} className="flex-1 rounded-t-sm bg-gradient-to-t from-blue-600 via-indigo-400 to-emerald-300" style={{height:`${b}%`}}/> )}</div><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>Aug 18</span><span>Aug 24</span><span>Aug 30</span><span>Sep 5</span></div></div></Card>
  <Card><SectionTitle icon={<Activity className="h-4 w-4"/>} title="System pulse" action={<Badge tone="green">● All systems operational</Badge>}/><div className="grid grid-cols-2 gap-3 p-4 md:grid-cols-4">{[["Agents","4/4 online"],["Data sources","3/3 connected"],["Evaluations","Running"],["Scheduler","Healthy"]].map(([a,b])=><div key={a} className="rounded-xl border border-slate-100 p-3"><div className="text-sm font-medium">{a}</div><div className="mt-1 text-xs text-emerald-600">● {b}</div></div>)}</div></Card>
  <Card><SectionTitle icon={<FileText className="h-4 w-4"/>} title="Recent documentation changes" action={<TinyLink>View all</TinyLink>}/><div className="divide-y divide-slate-100 px-4 pb-2">{[["Update OAuth authentication guide","docs/authentication.md • PR #142","In review"],["Add Redis caching guide","docs/redis/caching.md • Issue #87","In review"],["API rate limits documentation","docs/api/rate-limits.md • PR #138","Needs changes"],["Deployment guide for v1.2.0","docs/deployment.md • Release v1.2.0","Approved"],["Legacy auth migration guide","docs/migration/legacy.md • Issue #65","Published"]].map(([a,b,c],i)=><div key={a} className="flex items-center gap-3 py-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-blue-50 text-blue-600"><FileText className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{a}</div><div className="truncate text-xs text-slate-500">{b}</div></div><div className="text-xs text-slate-400">{["12 min","45 min","1 hour","3 hours","5 hours"][i]} ago</div><Badge tone={c==="Needs changes"?"amber":c==="Approved"||c==="Published"?"green":"blue"}>{c}</Badge></div>)}</div></Card>
 </div>
 <div className="space-y-4">
  <Card><SectionTitle icon={<FileText className="h-4 w-4"/>} title="Documentation by status"/><div className="flex items-center gap-5 p-5"><div className="relative h-32 w-32 shrink-0 rounded-full" style={{background:"conic-gradient(#10b981 0 67%,#3b82f6 67% 82%,#fbbf24 82% 92%,#f43f5e 92% 97%,#94a3b8 97%)"}}><div className="absolute inset-5 grid place-items-center rounded-full bg-white text-center"><div><strong className="text-xl">318</strong><div className="text-xs text-slate-500">Documents</div></div></div></div><div className="flex-1 space-y-2 text-xs">{[["Published","214","67%"],["In review","48","15%"],["Draft","32","10%"],["Needs attention","16","5%"],["Archived","8","3%"]].map(x=><div key={x[0]} className="flex justify-between"><span>{x[0]}</span><span>{x[1]} · {x[2]}</span></div>)}</div></div></Card>
  <Card><SectionTitle icon={<Star className="h-4 w-4"/>} title="Top documentation areas" action={<TinyLink>View all</TinyLink>}/><div className="space-y-3 p-4">{[["Authentication",88],["API Reference",76],["Getting Started",61],["Deployment",52],["SDKs",45]].map(([n,v],i)=><div key={n as string} className="grid grid-cols-[20px_1fr_90px_32px] items-center gap-2 text-xs"><span>{i+1}</span><span>{n}</span><Progress value={v as number} tone="blue"/><span>{[42,38,28,24,20][i]}</span></div>)}</div></Card>
  <Card><SectionTitle icon={<Star className="h-4 w-4"/>} title="Evaluation results" action={<TinyLink>View all</TinyLink>}/><div className="p-5"><div className="mb-4 flex items-center gap-4"><div className="grid h-28 w-28 place-items-center rounded-full border-[12px] border-emerald-500 text-center"><div><strong className="text-2xl">92%</strong><div className="text-[10px] text-slate-500">Average score</div></div></div><div className="flex-1 space-y-3">{[["Correctness",94],["Completeness",91],["Grounding",90],["Consistency",88],["Relevance",95]].map(([n,v],i)=><div key={n as string}><div className="mb-1 flex justify-between text-[11px]"><span>{n}</span><span>{v}%</span></div><Progress value={v as number} tone={i===1?"violet":"green"}/></div>)}</div></div></div></Card>
 </div>
 <div className="space-y-4">
  <Card><SectionTitle icon={<Workflow className="h-4 w-4"/>} title="Active workflows" action={<TinyLink>View all</TinyLink>}/><div className="divide-y divide-slate-100 p-4">{[["PR Documentation","12 min ago"],["Release Notes","28 min ago"],["Support Intelligence","1 hour ago"],["Scheduled Audit","In 6 hours"]].map(([a,b],i)=><div className="flex py-3" key={a}><div className="flex-1"><div className="text-sm font-medium">{a}</div><div className="text-xs text-slate-500">Authly</div></div><div className="text-right text-xs"><div className={i===3?"text-slate-500":"text-emerald-600"}>● {i===3?"Scheduled":"Running"}</div><div className="mt-1 text-slate-400">{b}</div></div></div>)}</div></Card>
  <Card><SectionTitle icon={<Bot className="h-4 w-4"/>} title="Needs your attention" action={<TinyLink>View all</TinyLink>}/><div className="divide-y divide-slate-100 p-4">{[["12 reviews pending","3 high risk"],["3 failed evaluations","Needs investigation"],["1 data source issue","Discord connection error"],["2 stale documentation areas","No updates in 30+ days"]].map(([a,b])=><div key={a} className="py-3"><div className="text-sm font-medium">{a}</div><div className="text-xs text-slate-500">{b}</div></div>)}</div></Card>
  <Card className="bg-gradient-to-br from-indigo-50 to-violet-50 p-5"><h3 className="text-lg font-semibold">Turn conversations into better documentation</h3><p className="mt-2 text-sm text-slate-500">Connect more data sources to help Draftly stay up to date.</p><Button className="mt-4">Add integration</Button></Card>
 </div>
</div></>}
